version: "3.8"

services:


  app:
    container_name: ${APP_NAME}-app
    build:
      context: ./app
    stdin_open: true
    volumes:
      - ./app:/app
      - /app/node_modules
    restart: on-failure  
    environment:
      - CHOKIDAR_USEPOLLING=true  
      - REACT_APP_ENV=dev
    ports:
    - "3000:3000"  


  api:
    container_name: ${APP_NAME}-api
    build:
        context: ./api
        dockerfile: Dockerfile
    volumes:
      - ./api:/srv/api
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    environment:
      - APP_ENV=dev
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASS}@database:3306/${DB_NAME}?serverVersion=8&charset=utf8mb4
      - JWT_PASSPHRASE=${JWT_PASSPHRASE}
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
      - MAILER_DSN=${MAILER_DSN}
    ports :
      - 9000:8000
    depends_on:
      - database


  database:
    container_name: ${APP_NAME}-database
    image: mysql:8
    ports:
        - "4306:3306"
    volumes:
        - ./docker/database:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASS}
        MYSQL_DATABASE : ${DB_NAME}
      

  phpmyadmin:
    container_name: ${APP_NAME}-phpmyadmin
    image: phpmyadmin/phpmyadmin:5.0.2
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
    depends_on:
      - database


volumes:
  database:

