# Read the documentation: https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/blob/master/Resources/doc/getting_started.md
coop_tilleuls_forgot_password:
    password_token:
        class: App\Entity\PasswordToken # required
        expires_in: 1 day
        user_field: user
        serialization_groups: []
    user:
        class: App\Entity\User # required
        email_field: email
        password_field: password


# config/packages/coop_tilleuls_forgot_password.yaml
# coop_tilleuls_forgot_password:
#     password_token:
#         class: 'App\Entity\PasswordToken' # Token class fully qualified name (required)
#         expires_in: '1 day'               # Token duration (optional, default value)
#         user_field: 'user'                # User property in token class (optional, default value)
#         serialization_groups: [ ]         # Serialization groups used in GET /forgot-password/{tokenValue} (optional, default value)
#     user:
#         class: 'App\Entity\User'          # User class fully qualified name (required)
#         email_field: 'email'              # Email property in user class (optional, default value)
#         password_field: 'password'        # Password property in user class (optional, default value)
#         authorized_fields: [ 'email' ]    # User properties authorized to reset the password (optional, default value)
#     use_jms_serializer: false             # Switch between symfony's serializer component or JMS Serializer